name: GitHub Actions Workflow

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
    - name: Send Webhook
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{"action": "${{ github.event_name }}", "author": "${{ github.actor }}", "from_branch": "${{ github.event.before }}", "to_branch": "${{ github.ref }}", "timestamp": "${{ github.event.head_commit.timestamp }}"}' \
        https://4896-2409-40f2-28-a132-810d-a664-3b0b-8aee.ngrok-free.app/webhook
